import type { Metadata } from "next";
import Link from "next/link";
import { AdminNav } from "@/components/admin/admin-nav";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import type { ConsultationStatus } from "@/lib/supabase/database.types";
export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Consultations", robots: { index: false, follow: false, nocache: true } };
const statusValues: ConsultationStatus[]=["new","reviewing","contacted","site_visit","proposal","won","lost","archived"];
export default async function Consultations({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){await requireAdmin();const params=await searchParams;const q=(params.q||"").trim().toLowerCase().slice(0,100);const status=statusValues.includes(params.status as ConsultationStatus)?params.status as ConsultationStatus:"";let request=createSupabaseAdminClient().from("consultations").select("*").eq("submission_state","complete").order("created_at",{ascending:false}).limit(100);if(status)request=request.eq("status",status);const{data,error}=await request;if(error)throw new Error("Consultations could not be loaded.");const rows=(data||[]).filter((item)=>!q||[item.name,item.email,item.project_location].some((value)=>value.toLowerCase().includes(q)));return <main className="admin-shell" id="main-content"><AdminNav/><div className="admin-heading"><div><p className="eyebrow">Founder dashboard</p><h1>Consultations</h1><p>Durable inquiry records and private follow-up details.</p></div></div><form className="admin-filters"><div><label htmlFor="q">Search</label><input defaultValue={params.q} id="q" name="q" type="search"/></div><div><label htmlFor="status">Status</label><select defaultValue={status} id="status" name="status"><option value="">All statuses</option>{statusValues.map((value)=><option key={value} value={value}>{value.replace("_"," ")}</option>)}</select></div><button className="button button-primary">Apply</button></form>{rows.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Received</th><th>Customer</th><th>Location</th><th>Status</th></tr></thead><tbody>{rows.map((item)=><tr key={item.id}><td>{new Date(item.created_at).toLocaleDateString()}</td><td><Link href={`/admin/consultations/${item.id}`}>{item.name}</Link><span>{item.email}</span></td><td>{item.project_location}</td><td><span className="status-badge">{item.status.replace("_"," ")}</span></td></tr>)}</tbody></table></div>:<div className="admin-empty"><h2>No consultations match this view.</h2></div>}</main>}
