import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminNav } from "@/components/admin/admin-nav";
import { ProjectPhotoUploader } from "@/components/admin/project-photo-uploader";
import { ProjectPhotoEditor } from "@/components/admin/project-photo-editor";
import { getSupabasePublicConfig } from "@/lib/supabase/config";
import { createProjectUpdateAction,setProjectPublicationAction,setUpdatePublicationAction,updateProjectAction } from "@/app/admin/projects/actions";
import { requireAdmin } from "@/lib/admin/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { isUuid,label,operationalStatuses,projectStages,publicBuildStatuses,PROJECT_PRIVATE_BUCKET } from "@/lib/projects/schema";
export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Project workspace",robots:{index:false,follow:false,nocache:true}};
export default async function ProjectDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{saved?:string;publication?:string;photo?:string;photoError?:string}>}){
  await requireAdmin();const{id}=await params;const query=await searchParams;if(!isUuid(id))notFound();const client=createSupabaseAdminClient();const publicConfig=getSupabasePublicConfig();
  const[{data:project},{data:updates},{data:photos},{data:captures}]=await Promise.all([
    client.from("projects").select("*").eq("id",id).maybeSingle(),client.from("project_updates").select("*").eq("project_id",id).order("occurred_on",{ascending:false}),client.from("project_photos").select("*").eq("project_id",id).eq("upload_state","complete").order("created_at"),client.from("field_capture_sessions").select("*").eq("project_id",id).in("session_state",["complete","partial"]).order("created_at",{ascending:false})]);
  if(!project)notFound();const signed=await Promise.all((photos||[]).map(async(photo)=>({...photo,url:(await client.storage.from(PROJECT_PRIVATE_BUCKET).createSignedUrl(photo.private_storage_path,300)).data?.signedUrl||null})));
  return <main className="admin-shell" id="main-content"><AdminNav/>{query.saved==="1"?<div className="admin-save-confirmation" role="status"><strong>Project saved.</strong><span>Your project information is up to date.</span></div>:query.publication==="1"?<div className="admin-save-confirmation" role="status"><strong>Publication updated.</strong></div>:query.photo?<div className="admin-save-confirmation" role="status"><strong>{query.photo==="saved"?"Photo details saved.":query.photo==="published"?"Photo approved and published.":"Photo returned to private."}</strong></div>:null}
  <Link className="admin-back" href="/admin/projects">Back to projects</Link><div className="admin-heading"><div><p className="eyebrow">{label(project.publication_status)}</p><h1>{project.internal_name}</h1><p>Private workspace. Public copy is marked separately.</p></div><div className="admin-security-actions"><Link className="button button-outline" href={`/field#capture`}>Field capture</Link><Link className="button button-outline" href={`/admin/projects/${id}/preview`} target="_blank">Preview</Link>{project.publication_status==="published"?<Link className="button button-outline" href={`/projects/${project.slug}`} target="_blank">View public Build</Link>:null}<form action={setProjectPublicationAction}><input name="id" type="hidden" value={id}/><input name="intent" type="hidden" value={project.publication_status==="published"?"unpublish":"publish"}/><button className="button button-primary">{project.publication_status==="published"?"Unpublish":"Publish Build"}</button></form></div></div>
  <section className="admin-card"><h2>Project information</h2><form action={updateProjectAction} className="admin-project-form"><input name="id" type="hidden" value={id}/><label>Internal name<input defaultValue={project.internal_name} name="internalName" required/></label><label>Public title<input defaultValue={project.public_title} name="publicTitle" required/></label><label>Slug<input defaultValue={project.slug} name="slug" required/></label><label>Public location<input defaultValue={project.public_location||""} name="publicLocation"/></label><label className="admin-wide">Public story summary<textarea defaultValue={project.public_summary||""} name="publicSummary" rows={4}/></label><label>Operational status<select defaultValue={project.operational_status} name="operationalStatus">{operationalStatuses.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Project stage<select defaultValue={project.project_stage} name="projectStage">{projectStages.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Public Build status<select defaultValue={project.public_build_status} name="publicBuildStatus">{publicBuildStatuses.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Start date<input defaultValue={project.started_on||""} name="startedOn" type="date"/></label><label>Completion date<input defaultValue={project.completed_on||""} name="completedOn" type="date"/></label><label>Private address<input defaultValue={project.private_address||""} name="privateAddress"/></label><label className="admin-wide">Internal scope<textarea defaultValue={project.internal_scope||""} name="internalScope" rows={5}/></label><label className="admin-wide">Private notes<textarea defaultValue={project.internal_notes||""} name="internalNotes" rows={5}/></label><label className="admin-check"><input defaultChecked={project.featured_on_homepage} name="featured" type="checkbox"/> Feature on homepage when published</label><button className="button button-primary" type="submit">Save project</button></form></section>
  <section className="admin-card"><h2>Field capture sessions</h2><p>Private notes and candidate media captured from Zarka Field. These notes are never public updates.</p>{captures?.length?<div className="field-session-list">{captures.map(capture=><article key={capture.id}><div><strong>{label(capture.project_stage)}</strong><time dateTime={capture.created_at}>{new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(capture.created_at))}</time></div><p>{capture.field_note||"Photo-only capture"}</p><small>{capture.completed_photo_count} saved · {capture.failed_photo_count} failed · {label(capture.session_state)}</small></article>)}</div>:<p className="field-muted">No field captures yet.</p>}</section>
  <section className="admin-card"><h2>Project photography</h2><p>Uploads and originals remain private. Candidate means selected for later review, not public. Publishing requires both a caption and descriptive alt text.</p>{query.photoError?<div className="notification-warning" role="alert"><strong>Photo details saved, but the photo was not published.</strong><p>{query.photoError==="details"?"Add both a caption and alt text, then approve it again.":"The approved public copy could not be created. The private original and your details remain saved."}</p></div>:null}{publicConfig?<ProjectPhotoUploader projectId={id} publishableKey={publicConfig.publishableKey} url={publicConfig.url}/>:<p className="notification-warning">Photo storage is not configured.</p>}{signed.map(photo=><ProjectPhotoEditor altText={photo.alt_text||""} candidate={photo.publication_candidate} caption={photo.caption||""} key={photo.id} photoId={photo.id} projectId={id} signedUrl={photo.url} visibility={photo.visibility}/>)}</section>
  <section className="admin-card"><h2>Progress updates</h2><form action={createProjectUpdateAction} className="admin-update-form"><input name="projectId" type="hidden" value={id}/><label>Update title<input name="title" required/></label><label>Story<textarea minLength={10} name="body" required rows={5}/></label><label>Stage<select defaultValue={project.project_stage} name="projectStage">{projectStages.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Date<input defaultValue={new Date().toISOString().slice(0,10)} name="occurredOn" type="date"/></label><button className="button button-primary">Save private update</button></form>{updates?.map(update=><article className="admin-update-row" key={update.id}><div><strong>{update.title}</strong><p>{update.body}</p><small>{update.occurred_on} | {label(update.publication_status)}</small></div><form action={setUpdatePublicationAction}><input name="id" type="hidden" value={update.id}/><input name="projectId" type="hidden" value={id}/><input name="intent" type="hidden" value={update.publication_status==="published"?"unpublish":"publish"}/><button className="button button-outline">{update.publication_status==="published"?"Make private":"Publish update"}</button></form></article>)}</section></main>}