/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";
import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
import { FIELD_NOTE_MAX_LENGTH, FIELD_PHOTO_BATCH_MAX, fieldStageOptions } from "@/lib/field/schema";
import { PROJECT_PHOTO_MAX_BYTES, PROJECT_PHOTO_MIME_TYPES } from "@/lib/projects/schema";
import type { ProjectOperationalStatus, ProjectStage } from "@/lib/supabase/database.types";

type FieldProject = { id:string; internalName:string; location:string|null; startedOn:string|null; completedOn:string|null; operationalStatus:ProjectOperationalStatus; projectStage:ProjectStage; updatedAt:string; latestCaptureAt:string|null; privatePhotoCount:number; candidatePhotoCount:number };
type SelectedPhoto = { key:string; file:File; url:string; caption:string; candidate:boolean; state:"ready"|"uploading"|"saved"|"failed"; message?:string; photoId?:string };
type Props = { projects:FieldProject[]; publishableKey:string; supabaseUrl:string; initialProjectId?:string };
const formatDate=(value:string|null)=>value?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value)):"Not scheduled";

export function FieldCapture({projects,publishableKey,supabaseUrl,initialProjectId}:Props){
  const initialProject = projects.find((item) => item.id === initialProjectId) ?? projects[0];
  const [selectedProjectId,setSelectedProjectId]=useState(initialProject?.id||""); const project=projects.find(item=>item.id===selectedProjectId);
  const [stage,setStage]=useState<ProjectStage>(project?.projectStage||"consultation"); const [note,setNote]=useState(""); const [photos,setPhotos]=useState<SelectedPhoto[]>([]);
  const [saving,setSaving]=useState(false); const [message,setMessage]=useState<{kind:"success"|"error"|"partial";text:string}|null>(null); const [sessionId,setSessionId]=useState<string|null>(null);
  const [installed,setInstalled]=useState(false); const captureRef=useRef<HTMLDivElement>(null);
  useEffect(() => { const frame = requestAnimationFrame(() => { const standalone = window.matchMedia("(display-mode: standalone)").matches || Boolean((navigator as Navigator & { standalone?: boolean }).standalone); setInstalled(standalone); }); return () => cancelAnimationFrame(frame); }, []);
  const groups=useMemo(()=>({active:projects.filter(p=>p.operationalStatus==="active"),upcoming:projects.filter(p=>p.operationalStatus==="planning"),recent:[...projects].sort((a,b)=>(b.latestCaptureAt||b.updatedAt).localeCompare(a.latestCaptureAt||a.updatedAt)).slice(0,4)}),[projects]);
  function chooseProject(id:string){setSelectedProjectId(id);const next=projects.find(p=>p.id===id);if(next)setStage(next.projectStage);captureRef.current?.scrollIntoView({behavior:"smooth"})}
  function addFiles(event:ChangeEvent<HTMLInputElement>){const incoming=Array.from(event.target.files||[]);const available=FIELD_PHOTO_BATCH_MAX-photos.length;const valid:SelectedPhoto[]=[];let error="";for(const file of incoming.slice(0,available)){if(!PROJECT_PHOTO_MIME_TYPES.includes(file.type as never)){error=`${file.name} is not a supported image.`;continue}if(file.size<=0||file.size>PROJECT_PHOTO_MAX_BYTES){error=`${file.name} must be between 1 byte and 15 MB.`;continue}valid.push({key:crypto.randomUUID(),file,url:URL.createObjectURL(file),caption:"",candidate:false,state:"ready"})}setPhotos(current=>[...current,...valid]);if(incoming.length>available)error=`Only ${FIELD_PHOTO_BATCH_MAX} photos can be saved in one capture.`;setMessage(error?{kind:"error",text:error}:null);event.target.value=""}
  function updatePhoto(key:string,changes:Partial<SelectedPhoto>){setPhotos(current=>current.map(photo=>photo.key===key?{...photo,...changes}:photo))}
  function removePhoto(key:string){setPhotos(current=>{const target=current.find(photo=>photo.key===key);if(target)URL.revokeObjectURL(target.url);return current.filter(photo=>photo.key!==key)})}
  async function save(){if(!project){setMessage({kind:"error",text:"Choose a build first."});return}if(!photos.length&&!note.trim()){setMessage({kind:"error",text:"Add a short note or at least one photo."});return}setSaving(true);setMessage(null);const clientSubmissionId=crypto.randomUUID();try{
    const start=await fetch("/api/field/captures/start",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:project.id,stage,note,clientSubmissionId,files:photos.map(p=>({name:p.file.name,type:p.file.type,size:p.file.size,caption:p.caption,candidate:p.candidate}))})});const started=await start.json();if(!start.ok)throw new Error(started.message||"Capture could not be started.");setSessionId(started.sessionId);const client=createSupabaseBrowserClient(supabaseUrl,publishableKey);
    for(let i=0;i<started.uploads.length;i++){const upload=started.uploads[i];const current=photos[i];updatePhoto(current.key,{state:"uploading",photoId:upload.photoId,message:"Uploading…"});const{error}=await client.storage.from("project-media-private").uploadToSignedUrl(upload.path,upload.token,current.file,{contentType:current.file.type});updatePhoto(current.key,error?{state:"failed",message:"Upload failed",photoId:upload.photoId}:{state:"saved",message:"Uploaded securely",photoId:upload.photoId});}
    const final=await fetch("/api/field/captures/finalize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:started.sessionId})});const result=await final.json();if(!final.ok)throw new Error(result.message||"Capture could not be finalized.");const failed=new Set<string>(result.failedPhotoIds||[]);setPhotos(current=>current.map(photo=>photo.photoId&&failed.has(photo.photoId)?{...photo,state:"failed",message:"Not saved — retry available"}:{...photo,state:"saved",message:"Saved privately"}));setMessage({kind:result.state==="partial"?"partial":"success",text:result.message});if(result.state==="complete"){setNote("");setTimeout(()=>window.location.reload(),900)}}catch(error){setMessage({kind:"error",text:error instanceof Error?error.message:"The capture could not be saved."})}finally{setSaving(false)}}
  async function retry(photo:SelectedPhoto){if(!sessionId||!photo.photoId)return;updatePhoto(photo.key,{state:"uploading",message:"Retrying…"});try{const response=await fetch("/api/field/captures/retry",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId,photoId:photo.photoId})});const result=await response.json();if(!response.ok)throw new Error(result.message);const client=createSupabaseBrowserClient(supabaseUrl,publishableKey);const{error}=await client.storage.from("project-media-private").uploadToSignedUrl(result.path,result.token,photo.file,{contentType:photo.file.type});if(error)throw error;const final=await fetch("/api/field/captures/finalize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId})});const done=await final.json();if(!final.ok)throw new Error(done.message);const failed=new Set<string>(done.failedPhotoIds||[]);updatePhoto(photo.key,failed.has(photo.photoId)?{state:"failed",message:"Retry failed"}:{state:"saved",message:"Saved privately"});setMessage({kind:done.state==="partial"?"partial":"success",text:done.message})}catch(error){updatePhoto(photo.key,{state:"failed",message:error instanceof Error?error.message:"Retry failed"})}}
  return <main className="field-shell" id="main-content"><header className="field-header"><div><p className="eyebrow">Private founder workspace</p><h1>Zarka Field</h1><p>What can I document right now?</p></div><Link href="/admin">Full admin</Link></header>
    {!projects.length?<section className="field-empty"><h2>No builds are ready for capture</h2><p>Create or reopen a build in the founder dashboard first.</p></section>:<>
    <section aria-labelledby="active-builds"><h2 id="active-builds">Active builds</h2><div className="field-build-list">{groups.active.length?groups.active.map(p=><BuildCard key={p.id} project={p} select={chooseProject}/>):<p className="field-muted">No build is marked active.</p>}</div></section>
    <section aria-labelledby="upcoming-builds"><h2 id="upcoming-builds">Upcoming builds</h2><div className="field-build-list">{groups.upcoming.length?groups.upcoming.map(p=><BuildCard key={p.id} project={p} select={chooseProject}/>):<p className="field-muted">No upcoming builds.</p>}</div></section>
    <section aria-labelledby="recent-builds"><h2 id="recent-builds">Recently updated</h2><div className="field-build-list">{groups.recent.map(p=><BuildCard key={p.id} project={p} select={chooseProject}/>)}</div></section>
    <section className="field-capture" id="capture" ref={captureRef}><p className="eyebrow">Quick capture</p><h2>Add progress</h2><label>Build<select value={selectedProjectId} onChange={e=>chooseProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.internalName}</option>)}</select></label><label>Stage<select value={stage} onChange={e=>setStage(e.target.value as ProjectStage)}>{fieldStageOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label>Short private note <span>Optional</span><textarea maxLength={FIELD_NOTE_MAX_LENGTH} onChange={e=>setNote(e.target.value)} rows={3} value={note}/><small>{note.length}/{FIELD_NOTE_MAX_LENGTH}. This never becomes a public update.</small></label><div className="field-file-actions"><label className="button button-primary">Take photos<input accept="image/jpeg,image/png,image/webp" capture="environment" multiple onChange={addFiles} type="file"/></label><label className="button button-outline">Choose photos<input accept="image/jpeg,image/png,image/webp" multiple onChange={addFiles} type="file"/></label></div><p className="field-muted">Up to 20 photos per capture, 15 MB each. Originals stay private.</p>
      <div className="field-photo-list">{photos.map(photo=><article className="field-photo" key={photo.key}><img alt="Selected field capture preview" src={photo.url}/><div><strong>{photo.file.name}</strong><small>{(photo.file.size/1024/1024).toFixed(1)} MB · {photo.message||"Ready"}</small><label>Caption <span>Optional</span><input maxLength={300} onChange={e=>updatePhoto(photo.key,{caption:e.target.value})} value={photo.caption}/></label><label className="field-check"><input checked={photo.candidate} onChange={e=>updatePhoto(photo.key,{candidate:e.target.checked})} type="checkbox"/> Public candidate for later review</label><div className="field-photo-buttons">{photo.state==="failed"?<button className="button button-outline" onClick={()=>retry(photo)} type="button">Retry</button>:null}<button disabled={saving||photo.state==="uploading"} onClick={()=>removePhoto(photo.key)} type="button">Remove</button></div></div></article>)}</div>
      {message?<div className={`field-message field-message-${message.kind}`} role={message.kind==="error"?"alert":"status"}>{message.text}</div>:null}<button className="button button-primary field-save" disabled={saving} onClick={save} type="button">{saving?"Saving securely…":"Save field progress"}</button><p className="field-privacy">Nothing added here is published. Candidate photos must still be reviewed and approved in the full admin workspace.</p></section></>}
    {!installed?<details className="field-install"><summary>Install Zarka Field</summary><h2>Add Field Mode to your phone</h2><p><strong>iPhone:</strong> Open this page in Safari, tap Share, then Add to Home Screen.</p><p><strong>Android:</strong> Open this page in Chrome, open the menu, then choose Install app or Add to Home Screen.</p></details>:null}
    <nav aria-label="Field Mode" className="field-bottom-nav"><a href="#active-builds">Builds</a><a href="#capture">Capture</a><Link href="/admin">Admin</Link></nav></main>}
function BuildCard({project,select}:{project:FieldProject;select:(id:string)=>void}){return <article className="field-build-card"><div><span className="status-badge">{project.operationalStatus.replaceAll("_"," ")}</span><h3>{project.internalName}</h3><p>{project.location||"Private location"} · {formatDate(project.startedOn)}</p><small>Stage: {fieldStageOptions.find(o=>o.value===project.projectStage)?.label}<br/>Latest: {formatDate(project.latestCaptureAt||project.updatedAt)}<br/>{project.privatePhotoCount} private · {project.candidatePhotoCount} candidates</small></div><button className="button button-primary" onClick={()=>select(project.id)} type="button">Add progress</button></article>}