"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/admin/auth";
import { PROJECT_PRIVATE_BUCKET, PROJECT_PUBLIC_BUCKET, isUuid, operationalStatuses, projectSlug, projectStages, publicBuildStatuses } from "@/lib/projects/schema";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import type { ProjectOperationalStatus, ProjectStage, PublicBuildStatus } from "@/lib/supabase/database.types";

const text=(form:FormData,key:string,max=5000)=>String(form.get(key)||"").trim().slice(0,max);
export async function createProjectAction(form:FormData){const user=await requireAdmin();const internalName=text(form,"internalName",160);const slug=projectSlug(text(form,"slug",120)||internalName);if(internalName.length<2||!slug)throw new Error("Project name and slug are required.");const{data,error}=await createSupabaseAdminClient().from("projects").insert({internal_name:internalName,public_title:text(form,"publicTitle",160)||internalName,slug,created_by:user.id,updated_by:user.id}).select("id").single();if(error||!data)throw new Error("The project could not be created. Check that the slug is unique.");redirect(`/admin/projects/${data.id}`)}
export async function updateProjectAction(form:FormData){const user=await requireAdmin();const id=text(form,"id",36);const operationalStatus=text(form,"operationalStatus") as ProjectOperationalStatus;const projectStage=text(form,"projectStage") as ProjectStage;const publicBuildStatus=text(form,"publicBuildStatus") as PublicBuildStatus;if(!isUuid(id)||!operationalStatuses.includes(operationalStatus)||!projectStages.includes(projectStage)||!publicBuildStatuses.includes(publicBuildStatus))throw new Error("Project fields could not be validated.");const payload={internal_name:text(form,"internalName",160),slug:projectSlug(text(form,"slug",120)),public_title:text(form,"publicTitle",160),public_summary:text(form,"publicSummary",600)||null,public_location:text(form,"publicLocation",120)||null,private_address:text(form,"privateAddress",300)||null,internal_scope:text(form,"internalScope")||null,internal_notes:text(form,"internalNotes")||null,operational_status:operationalStatus,project_stage:projectStage,public_build_status:publicBuildStatus,featured_on_homepage:form.get("featured")==="on",started_on:text(form,"startedOn",10)||null,completed_on:text(form,"completedOn",10)||null,updated_by:user.id};const{error}=await createSupabaseAdminClient().from("projects").update(payload).eq("id",id);if(error)throw new Error("The project could not be saved.");revalidatePath(`/admin/projects/${id}`);revalidatePath("/projects");revalidatePath("/");redirect("/admin/projects/"+id+"?saved=1")}
export async function setProjectPublicationAction(form:FormData){await requireAdmin();const id=text(form,"id",36);const intent=text(form,"intent");if(!isUuid(id)||!["publish","unpublish"].includes(intent))throw new Error("Publication request is invalid.");const client=createSupabaseAdminClient();const{data}=await client.from("projects").select("public_summary").eq("id",id).single();if(intent==="publish"&&(!data?.public_summary||data.public_summary.trim().length<20))throw new Error("Add a public summary before publishing.");await client.from("projects").update({publication_status:intent==="publish"?"published":"unpublished",published_at:intent==="publish"?new Date().toISOString():null}).eq("id",id);revalidatePath(`/admin/projects/${id}`);revalidatePath("/projects");revalidatePath("/");redirect("/admin/projects/"+id+"?publication=1")}
export async function createProjectUpdateAction(form:FormData){const user=await requireAdmin();const projectId=text(form,"projectId",36);const title=text(form,"title",160);const body=text(form,"body");const stage=text(form,"projectStage") as ProjectStage;if(!isUuid(projectId)||title.length<2||body.length<10||!projectStages.includes(stage))throw new Error("Update title, story, and stage are required.");const{error}=await createSupabaseAdminClient().from("project_updates").insert({project_id:projectId,title,body,project_stage:stage,occurred_on:text(form,"occurredOn",10)||new Date().toISOString().slice(0,10),created_by:user.id,updated_by:user.id});if(error)throw new Error("The update could not be saved.");revalidatePath(`/admin/projects/${projectId}`)}
export async function setUpdatePublicationAction(form:FormData){await requireAdmin();const id=text(form,"id",36),projectId=text(form,"projectId",36),intent=text(form,"intent");if(!isUuid(id)||!isUuid(projectId)||!["publish","unpublish"].includes(intent))throw new Error("Update publication request is invalid.");await createSupabaseAdminClient().from("project_updates").update({publication_status:intent==="publish"?"published":"unpublished",published_at:intent==="publish"?new Date().toISOString():null}).eq("id",id).eq("project_id",projectId);revalidatePath(`/admin/projects/${projectId}`);revalidatePath("/projects")}
export async function updatePhotoPublicationAction(form:FormData){await requireAdmin();const id=text(form,"id",36),projectId=text(form,"projectId",36),intent=text(form,"intent");if(!isUuid(id)||!isUuid(projectId))throw new Error("Photo request is invalid.");const client=createSupabaseAdminClient();const{data:photo}=await client.from("project_photos").select("*").eq("id",id).eq("project_id",projectId).single();if(!photo)throw new Error("Photo was not found.");if(intent==="publish"){const caption=text(form,"caption",300),alt=text(form,"altText",300);if(!caption||!alt||photo.upload_state!=="complete")throw new Error("Caption and alt text are required before approval.");const{data:file,error:downloadError}=await client.storage.from(PROJECT_PRIVATE_BUCKET).download(photo.private_storage_path);if(downloadError||!file)throw new Error("Private original could not be read.");const publicPath=`projects/${projectId}/${photo.id}.${photo.mime_type.split("/")[1]}`;const{error:uploadError}=await client.storage.from(PROJECT_PUBLIC_BUCKET).upload(publicPath,file,{contentType:photo.mime_type,upsert:true});if(uploadError)throw new Error("Approved copy could not be published.");await client.from("project_photos").update({caption,alt_text:alt,approval_status:"approved",visibility:"public",public_storage_path:publicPath,published_at:new Date().toISOString()}).eq("id",id)}else{if(photo.public_storage_path)await client.storage.from(PROJECT_PUBLIC_BUCKET).remove([photo.public_storage_path]);await client.from("project_photos").update({visibility:"private",public_storage_path:null,published_at:null}).eq("id",id)}revalidatePath(`/admin/projects/${projectId}`);revalidatePath("/projects");revalidatePath("/");redirect("/admin/projects/"+projectId+"?photo=1")}
